apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "0" # Ensure secrets are applied before other resources
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: luxe-backend
  source:
    repoURL: https://github.com/princewillopah/LuxeCart-GitOps.git
    targetRevision: main
    path: apps/backend/secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true