apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
  labels:
    app: elasticsearch
    tier: monitoring

spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
      name: http