{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-migration
  namespace: {{ .Values.namespace }}
  # annotations:
  #   "helm.sh/hook": post-install,post-upgrade
  #   "helm.sh/hook-delete-policy": before-hook-creation
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded

spec:
  backoffLimit: {{ .Values.migration.backoffLimit }}

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: flyway
          image: {{ .Values.migration.image }}

          command:
            - flyway
            - -connectRetries=10
            - -baselineOnMigrate=true
            - migrate

          env:
            - name: FLYWAY_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.migration.db.secretName }}
                  key: {{ .Values.migration.db.urlKey }}

            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.migration.db.secretName }}
                  key: {{ .Values.migration.db.userKey }}

            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.migration.db.secretName }}
                  key: {{ .Values.migration.db.passwordKey }}

          volumeMounts:
            - name: migrations
              mountPath: /flyway/sql

      volumes:
        - name: migrations
          configMap:
            name: postgres-migrations
{{- end }}