apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{ .Values.namespace }}
  labels:
    app: kibana
    tier: data

spec:
  type: {{ .Values.kibana.service.type }}

  selector:
    app: kibana

  ports:
    - port: {{ .Values.kibana.service.port }}
      targetPort: 5601
      name: http