prometheus:
  service:
    type: NodePort
    nodePort: 30090

prometheusSpec:
  retention: 7d

  # 🔴 FIX: allow all ServiceMonitors
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}

  podMonitorSelector: {}
  podMonitorNamespaceSelector: {}

  additionalScrapeConfigs:
    name: prometheus-additional-scrape-configs
    key: additional-scrape-configs.yaml

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi

  scrapeInterval: 15s
  evaluationInterval: 15s




# prometheus:
#   service:
#     type: NodePort
#     nodePort: 30090

# prometheusSpec:
#   retention: 7d

#   # 🔴 THIS IS THE MISSING LINK
#   additionalScrapeConfigs:
#     name: prometheus-additional-scrape-configs
#     key: additional-scrape-configs.yaml

#   serviceMonitorSelector:
#     matchLabels:
#       release: prometheus

#   serviceMonitorNamespaceSelector:
#     matchNames:
#       - luxe-observability

#   resources:
#     requests:
#       cpu: 200m
#       memory: 512Mi
#     limits:
#       cpu: "1"
#       memory: 1Gi

#   storageSpec:
#     volumeClaimTemplate:
#       spec:
#         storageClassName: standard
#         accessModes: ["ReadWriteOnce"]
#         resources:
#           requests:
#             storage: 5Gi

#   scrapeInterval: 15s

# grafana:
#   enabled: false

# alertmanager:
#   enabled: false