namespace: luxe-infra

rabbitmq:
  image: rabbitmq:3.13-management-alpine
  replicas: 1

  auth:
    secretName: rabbitmq-secret
    usernameKey: RABBITMQ_DEFAULT_USER
    passwordKey: RABBITMQ_DEFAULT_PASS

  persistence:
    size: 10Gi

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

  ports:
    amqp: 5672
    management: 15672
    metrics: 15692

  config:
    enabled: true
    existingConfigMap: rabbitmq-config

  plugins:
    enabled: true
    existingConfigMap: rabbitmq-plugins

exporter:
  enabled: true