apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  namespace: luxe-frontend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
    prometheus.io/path: "/metrics"
  labels:
    app: nginx-exporter
    tier: presentation

spec:
  selector:
    app: nginx-exporter

  ports:
  - name: metrics
    port: 9113
    targetPort: 9113

  type: ClusterIP