{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "luxecart-sa" .Values.serviceAccount.name }}
  namespace: {{ .Values.namespaceFrontend }}
{{- end }}