apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: luxecart-db-migration
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50" # Ensure infra resources are applied before backend and frontend
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: luxe-infra
  source:
    repoURL: git@github.com:princewillopah/LuxeCart-GitOps.git
    targetRevision: main
    path: charts/db-migration
    helm:
      valueFiles:
        - ../../environments/dev/infra/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # - CreateNamespace=true
      - PruneLast=true # Optional: prune resources last