apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "0" # Ensure infra secrets are applied before all other resources
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: luxe-infra
  source:
    repoURL: https://github.com/princewillopah/LuxeCart-GitOps.git
    targetRevision: main
    path: apps/infra/secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true