---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: elasticsearch-connection
  namespace: luxe-infra
spec:
  encryptedData:
    ELASTICSEARCH_URL: AgC42GlEfnrNh9TSh7f1xvDhnpcvqVUWbhI2YpVvkCtDq9CN4KciwuKa/XxMwi7o4EAr9r4703x29a/C9mSFfMEk6h9QsRFkKOyMfxgSHh41Uwy+Roa6xs9BPwN7qM9AAujMibA+6sXaRFv5g5jmYqPmG/4pbsg182mcZRKpoIRKLkxCy6zmwEQGhYqwj6xjInkykDQFxAA6DCurSdjwajxr4+XAWU+iEonBtSr9SJIuT6wO1t7FhmQSpm5E/OfQfx/DIrcQq2T19FAHguJchaAxLKBfujC+1xUqpBznisaFn5mzPEbfFqepPLk5U5nXgAwZjSosFnM0YRir5BTm44+4fGflQXignESxXPpZPDut4xaFOqDrjelv73X7WnJz2HA1TFwaqmFGqyxeesAyu3TOln6NC+CBrwmLXHi1HGe+d6wayV+uyoqXNQEsB6NzBPwR0LVsB+fdHrLCaNvHKKvwxPmcuLdFSwmGuakZACAdCsiegvLusv5mSP9Axp7uqdNcCpxuhb4/TOn9BGvwPEYE1kCEFocAjTc/H6ZQHUZZ2FI2jDrxHOgEaew7iLIfx6p5GXKh5076KPyQwNv7cYj836ilwVhy+dBb5mISXTjKRB9VCLm7JxRD/aXzla21BhM3U5eaIuZwtCFMExXckJBQCn4FritJtgblisNCfLTYQwdl+tLtxtil0AHbxFYua9z+ErJcYGxmZDemK6HJgeU2tPhhjZNQhDd5oFUeedXNXUV/5Od7e9Y1TuOO2CE5PhOfsDSzcv4=
  template:
    metadata:
      name: elasticsearch-connection
      namespace: luxe-infra
