---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: elasticsearch-connection
  namespace: luxe-backend
spec:
  encryptedData:
    ELASTICSEARCH_URL: AgAnlywMQk7/4RWx7zHnVpZcYQGKWCcs7oI78e837asgk7P6HzBwvpqLuebPZ31i1EVT/GXcaJ94unsG0RZv6/PgnUa0RyrpV8tc26RTS3DO08M7riM+T/WTLLaLmmy3g22YzCIRP9gTzUv22/jPzjuPTj8Y+tvlMCXP5tFMUEftcTxgAskddEvmZYf9+cbiwOXXnPwOIme0vZH2rRHhL0z2eihq+QFa5b6EumVEIJveK9AHr6sKRHqScemnJEiGn5J7SWpNqZ2eCseSB/tPYwJGxFLUgZIjdqRauMdR0M+YV7+ZznPvv77GsCURYYrdQ5pnx0nUOjKHbTM/+i85cw981o8K5HObkVVCX/1X3p6itRQdod2DXzYvNO8ce8XTKZgeSnfdN7cxmofPkiq2cFEj9oFYcuZThDpL5zCNrJuBlebom0p3HGYNK+PeLG4yXVryXZJh7HU0252KA8mUX9lla1RNnSFS2l2OIvbyXE5Wuq4mpEUbipTVsAGUGnTxuwdTHMFfSBYYK3jowpPoXCqjdSpdqlDAQJ1EkbiT3emKoszZapD9Kp4xZHdcnubqAN/23nOMEHAoOAsXeddgDychNcYH84GTZIX/ocAZE5TEkIuFKcgsTdjk1j0Ai0vmiwhQKplpT+AUEN+TAcEgtlOS0LH/n+pnCwPPBwIT2ZHnt8OHQcuQ/mS4r4Kw88i6OzICKFsw+ibVk5iL22t+sS39N9Y/6U/SjivEx8b46+xKQgWXpjH7vjfNfmjnW3aSUOGpHomezzQ=
  template:
    metadata:
      name: elasticsearch-connection
      namespace: luxe-backend
