---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-auth-secret
  namespace: luxe-backend
spec:
  encryptedData:
    JWT_SECRET: AgCHr1T0R4lY7wdqKChFYG7I+phv+5qzMiZWcQY0ZBoY1t5VhzbncUgkjXnheu5laSV2VS4A56I8Ql2dsaau9w5vPj8HKv7rb082uIqhNaMIqE5DNO1adB/BIZGh5sqHlt1la6jD3SygBUuXyE21D3ED7gVymOkI6vBsNFr3n8zk9Gt/0MhbTRaCXphC81W950gj1s2TYLwAKDKkmlhTD/5tVKEP8lhCNOtlrD7FkU5YTLfGXqw0CIgFS5XQwIVNt+hAJfNpamuF/R/YOWOzrYHv+AP62MYaQ/eS/sRSbHDTiCXTtGxS9zrekxTQniSAHzEs/PRNRJ9Yt9eDv4dTZWM3RurSJde4DRwnDalmUpLycm0uJfTm3HPYbz2VAG8CGXqwaAmQ2Y3yvXplJM9KEUZTuVKpjr60QiYpanR0pkxnOGFMvgtdL9COqWCAXRCI20/Ez6KlZRMlmbqsA4EyFPhNHg00+sRqKf6IsU8azg/J+8XJnGkMnrWjCKHMJyT5ceWFE0VxRK1ceV4r115pteJyuJf6KEaQdAfVps+wFECRHEZBIp71fk+EyzU6HcF+K9CWAlU8uZgFTQbHR+lc0T8EVWQ0g6/OSla8o64LgiuJdyeGy/NSE9iJVof9SF6jiKLaK5feiwxTcaQ5UAFyM7hMUMOQ4tCXr8ahLeE0qzS0Lii2kigkGmFKSewGfhSfLaWjD/pfm3hnZbP/z+EDSJPni3MirIQSH3cbOp7v07Ol6isPLGw=
  template:
    metadata:
      name: jwt-auth-secret
      namespace: luxe-backend
