---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-auth-secret
  namespace: luxe-infra
spec:
  encryptedData:
    JWT_SECRET: AgAjObira3+lAx1kc5kVUqpG2yB2c+CGFpEPHKdPeCAC0zaUNz4FX3p91EKRd3xcQFsMYDELWi+3sp4eyI3Fg9FG2uttBx4rfRTqrbCAJyijz24uP1YMsVkwrhi/iThu4eH/3fo1yI5iooFXWz8uBe/1c05y6iOirobzjzH6lV6129mtKBwplFNU4VGAWluE70l7VWPSz7j3xj6qOgF1e3XJEzhe8wnsOKBm9bv9sSjyodNVP2nVzW1gJIl3T0NWzk6CC11Nc1dPlHJr1jJEWel6Illrao3tlb++ficc0abGqTRCWUUkqeBqEjrHtmr1M5SGaPG3WWDmwn0m9hdjRP1J8YC52zJaZUaNLiNALl05cwYKN5/CekXfd6AYUZJKfv70ZYbYCowE/k0BAC3R23guOMAY8MFHAFl7godHj7Ia599zhIUhkaHHnq1FtvXJ5W5rKvdIwnn6XgP8tV0Wwx2XpsmgDzyJewRzUIXYWlh96eIfMalRpFJ3b1gCYzPqGGLHgKNyR7U2e1k0Pcef6zK6hctG8uGbcss7hmO2IuCARwswKSiIiFmLe6KN8gCXnE66H7EvPtRNoY6ZeNFyxHxMPM2JtE0Bi2yWyzsMNtjf09nnfNcmzDMWL4SbC2jSIqlfJ7IZ/DmUfPb0tNvVewZ4oTzQqHdR4JaAERjXpvNCLv4Bz6kR9075qZ2+rrFecJilNStHCA8hHwcTnIcxgi0UQ42WYL0Y3YkQmRyiLcUfIWCJYvE=
  template:
    metadata:
      name: jwt-auth-secret
      namespace: luxe-infra
