---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-connection
  namespace: luxe-infra
spec:
  encryptedData:
    MONGODB_URL: AgBu8fChwhFoX5F6DlUUVXYVDIEDFcq7fCiZKaAm+0pPto54TeOQK+0aUafqxWm83iBCMYC3zITFyQrVxuf1dsGY7i2mFrqLr/datLjn5lp0UrT3Fms3zD9J7wMxXApJzhHqFtv2QkY98/IiFNBKMTKAbC04iH9SJN2StO6WEQD9AQXtU3BHTweglBxTVDJkqEvEX3es/9LeiuaCu7bqVSrKlj9JO6DwHhZHDg8POA9FtKZ8ZFSM9gYMhghWh1SLeZvZJ0GD+YtUbVXHncPSwJcDe/IaSZZjRM+tcpFdRkcgX0thls5gwDUgdySfFNTVwW7p8QPoShR7Xge/OiRBLo33fOJUjojGbVzqyHe/8/LMK65CYRF2naoJWzKOhQM+ZUlLNYWXIPq3UlEVdkcHDUEDNu52iELiJJooR6NqZ3ZHLMFYMjhBJRYQWDwmLqynFZn43PFM+OW8Q4gr9csZRCFR/3HxtLXlGpW7L+iuSq9TGcrkTizoc5sDmQ/6ZoY4XX3iCmYfe1v8WMIjlkFkPT6l6xIkU5z6d4RJTt5NiNDDXoMCWIyHlPlRtqx+c37f3jDTb0xuUJOUVd6sWEKPwu0FysRRdGntpyMwahMltBYOkyy8WB2ZngRnLODxDAVLggeY/pUm8/8DbM8+xty68KKx0UhqFT0MmSK8cKZwSgqJJHrJrhYQBeMwbjh1HhUMRgoNOoLaCZlYIuYGlQ6ZPLFM5/iZxhIBMPYhKsKPe0od/Bnp7FnJpryZmUNqlQrKOF7yY+r2yBhf11w0zgOWCgwNX85yaC9/D+lJNcyF2BQ3GlAmuQqwhFEe6FwIYjth3q0nSTb61vzG750cJ7Bkh1E1fnNBA0U=
  template:
    metadata:
      name: mongodb-connection
      namespace: luxe-infra
