---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-connection
  namespace: luxe-backend
spec:
  encryptedData:
    MONGODB_URL: AgCZNgtM8qxlYeuwdKPzVMiSqQXrz1ARcXplzhTzr1dhXajaSxgs0ok3A6yLRXI3qD5II8sOtDx5L18LmPcpW2UMPax2Drw1p8kGfAp4FVp5K2oo+YvvUdtdS4cvo82JmDe5d35JmS3Hl7gp3cn5bOjYwjeMSNnfTYefCB3JGhaziTT3N27eHPkygUHYBRS6WUyu3+d2uiu0TBx/XrLJwFgzVpTnEXqjSZmd8G3fK8mvXTPKY1yc3J126CL9NMC8UQdQhVlhb7msAyK2Fhd7qR67BmKrGSSpwp2CFQB+EcDwEvXlnu6sc+Oq6sSyBgELHLKr4xU6zbIWdTrTANh+hrIr6euBn/1XrasEKG+WkxoPydUEp0vUgZNl7K1sTwhq2Q2hDz5Lv9GxGBhjOglTPy2dTsTiPzK+sYa7iywVHjcRUCqs7Szz8G2LPj5EPEjxHFq5lAFPQ9srX6Bkp5KkHNU0Kn0MFHjzFWmqGmVeU8T/HmZ6JQC+Bn7JHsvBSPSuDAfXIGB292u+5+WzRP4Rd5yLqSUu4QnGeh83cn/+Pk5yJDSHLjHvGHvgBNQOQnvqkZ3XfdPeyH1vOvfBj2LArTmUBtWu73HG8VSSV78FGteOy3LsEScgxB2MVzgohW1m4yu25a26Xqwz6gPtGcZt03ij85LZ5ZIdRfUVfCl6M23pyuNk035eOvtRruoZB5L33Z6kz4SEEYjpEvGkQO76AMU72W9AQMnj2cgomGrgUyRDChcVbo/hwq0lh7xshUDArrFhYlagN0GhB1OKSYBMgJ6ePmikRlVw3VKQaxTANzvQNeCd2uBWmgKe+mW3whkuu/EzzlIUSEospiVpKs7snugu/JTnmds=
  template:
    metadata:
      name: mongodb-connection
      namespace: luxe-backend
