---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-connection
  namespace: luxe-infra
spec:
  encryptedData:
    DATABASE_URL: AgCRq5jATO6bu2NeMmfwZn00b50wSjjXFn/63TKP3muvtiBltbEnuoXJYNp0W7+Qi3fjgUaEhapzd3htSbwSX6mwoJGIaHhC7uO4Hfvnb+mP0h+tVWeYVSFPEQme86QzOuVHVfyifRrqkQM2VeF2LVthR7x1iKm9s3vWuN3K9sk368lZc9Sg6Wd3F1V+IIwezlk53UWzw7iQZtTQKMKISr8DYUjBdLaZ1kI72KKDCFIntKpUOdeMeLjEYC9jILnUB8uvJg89R9Ws90Ate1uybf8DWUJ8VY01GW1VhhjAG84f7Aspecc/OuJusYMUH6cBM9zt4mUODVUb6Ji0lZEqB6TSj+ohmaXhfbjxDW2dDaUTonIpmV2y4xUiKVqUiiuMDkSVtE9j9VPstmHF32lU0qw1btruxng2jdWq1vmgiI0e9ItTwDVzNaC0rtUmKpQPzkIbAWbo65srkHrhWgUqlpDPNE+EndQJ7JQuKJrF3whuf7kvMmyshbP3ZWZiCYj+k9Zw36a2UdIV9qc3wrQPM/Zy035dlZ66USvJwkfgEz0RPHxm+EGmmfvNewjt0Tw4jki4Okq/SxgSUY3ij6yZIOrpqUTl6MF5M3nmFmXswAZl4ZEVxO56kOiWdJmobJQpww0x5sl0k+UkuGo5CCvKGbPiD1gH6KbzLT7IpSGCE3X/uO35tQ/ziv+8nPYKBIGI3He0QGEwkfgV8JIVRn6LtQxQvp4C6g1e8VtbRtoNRfCI1h3HtvcMDrrTxj8Ea7r7xIjnZfBDPk6J1LkzEKXAX6v4bbwAk8eNEyv5MDIkouK/4cQaBSIy8tos
  template:
    metadata:
      name: postgres-connection
      namespace: luxe-infra
