---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-connection
  namespace: luxe-backend
spec:
  encryptedData:
    DATABASE_URL: AgARzJAtDHgF5jm6yQp01Wdgbi+EJUsFiIzwYFbADPoUN5Tp7RpmvLU5r7ygGUwrF3UW5W26twlceO+0U8z6AmvTh5ztkbjDTmM40Od+Dm3HMa8MhAFfOKJOApRySJNZ3R2bAF23uX3AlcJJHlYwW3q2GqQ1lYi++rOEfI8il5epIwiZISbCZYuGMHO7RRhadD+Os/gF7peAqAlMAHgw6uOTLaab8PnzNyCmNieoJVf2QER3P2X0ziBI/Fq1g4LEnFVn36aF6jragTICbVw/jEZZ3ee3TnAiirdu6hgKlIdaDl7awAieGIAQ1/UvgnG633nxso9No1/4Uahf2PJ5VWilGWoOF5xKZQUEXT17ACkjMUaTIWNaAizE/GoLYjpi93QljkafkRLRHefAmOkqheQ31+jsrnazdf9IqK67rDkNQpKGf4Ev2AvExG7fgegkJtHVpEY/69rGjtSdOVhTjIUX76EArg8k+MBgvlzIPQBO5aseYEGw6Vr6+U0X4fcspm9hWXYQnMG7RpaB5RiugIELQrGVOUOJ+Rd8i3zf5wfHNGFgcDvrPaJwuC7NrOSe9FFmBfnrMVq6wNDWCbodKCEs8nsKOxsaLmEUkRuliaBaACpR//9DX2gSprpQSzWxzhJzs/9zyobCs67a1wYtVLlq61F5BVefE1jaX6BaeKOuW22Pl7ycXeG6Rued8HjtDz7+87C6heu07bPgAps3SSkKj4tn6YfbxQ0iVY3lmFV6dWu8cetkqxYzhI0x8DnwhWYuyGBvAUNvTINKMOdUEBQKFiWJ7xNQ+7j1PTHBDFGOa7DTTRfrg/hu
  template:
    metadata:
      name: postgres-connection
      namespace: luxe-backend
