---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-connection
  namespace: luxe-backend
spec:
  encryptedData:
    RABBITMQ_URL: AgAUBqS8XNm1ykHBR7Oo7Mm0hrlDdczuH0QS7JPjTpZwvsCZP+uHlhodHKbblq5QOdRfRmjgzE1Jk36xLkrbwybOyE91XeGQjyNU4yNTL9aVhZqqfNuCqAj3hEsam6dqQtKLniSR/8hAIe6eohCAg6tMdhV4s96y7SC4Q3tuW0+IzUVfoqdBZj39QMLJ80YySHcLiZcglbymmfPAgUYI8OOmI3+pTpBcjzx/7+HG1qRtky3hRbUicLNDHVhr/i03Jbd/7v4Y/ctJ27ey2OsMLgjSrMhWIt+xLFEh228kgnbBa+L392jC9bh2azxldmrlEyVjAxlUhUvcpzu7LjN4GpSllVz53YgYDD4d0wrbIFkubgCCBk46JwfiJDJwI6FGgqNhjMY0iaz0wTVb7P6PwVxOtAnym8zlECk9ZiPuG2O82h0lA6+FV2VXRSa/yxtEHGogfangaDaJkPvDPAP//DjxYTQoBMyuVGpk+tLpNWiBTyEFosccEQa+6XAJS4YJ3bz7D042kHsOEZuZoxJsFr9Mnq3dyuhXvf3JfZ+EegCkxQTz61V9rbPpz4iILe4wQ+XbHAAk3Vrw9Vbnh4U3oHaLxt6HfFmOKFMPwu7Xpo+W8eAzH/ciBEaM+mEVn5rU8SyouOQuLNUnEKudK7cig5vOgcKk/VmzUKAytNedah8GHjKD8hjSlqYbn4bqyvQJK9Wfp3Q/Ped15GA/P16r/ybLQcPBkzpQCY2ZuHoDoQKMmk23pVx4l06kprzkiYHUkREIc7Iw70TXPjRDYUjdY+wz2AoLLW+VDCxLNyjiJs/SCpxt
  template:
    metadata:
      name: rabbitmq-connection
      namespace: luxe-backend
