---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-connection
  namespace: luxe-infra
spec:
  encryptedData:
    RABBITMQ_URL: AgCH+fwSpKHbHr14+ZeeJr+bKQtZscx3PVwv5Tr/Rr8Lye4o2sxaXjN6rNHaNm9+R7rCxVPftecsbDLvSti79PlT+dJpSsYjDZNuoGHS8aFRYQgtMgxeFnfBMxiShtiTlcj+iorJgx9Zudnz8WIdzFw3mXFGS2JFdB0xML3ChLxKe0z9OyZ+DK480fRUxoOZNfM2NXdE89mmb5XEJaWsss3IZDNfZciF8HMj4ZNxjdbkdxTitv6pqIWoPSIXh9TCKKoXl8Imu6JW3rmiodMqTyuJEXe/5j2X81jtA8VEQfU3/wuhrng5TyflQ5GTlCXXAhNSARPcAjc1+Z5mgRlZv2+kfj5AIX0UkN6YdCqsWwdoh2tg1JfRXzQ+LfJRoCOqMm38nqk9Cvk+nChPko2DtIFY8ccYBXwMeXEtazOXUHU7upmLIhCh2YB6CsE9pDMM4hBoS2TY0ZXNZsHfn6MJe37YU+Oq9z18zx1+jlJnORDthnBMhk1u8BcvkJLeqhLPVpkeqRwzXGUAif1so/xzoPF2PttQDSEeHYmacq3u/Ig5uia2NnZDjAfQ055+FbDD9RRijTZTmCLSqo5kDMd6o/fvCV0XfuYMU4nJAFqAFkvEkeGO0ah+H/x8YkoiB6lRxlAI9HFOWwi49CZpyW6i1RP/YAgTvb+nzys5cwRvXMn/7pWGCjK/FVvhl0qelBRLKG9hwPlD17Hda1bfhylNofEnPp10jhs4A91DpveRiKb1aoWNWn2A/kp1VOI7u8nDd40TdO1plTJwW4GCu0ifk6pBkIbGiqAL7GlJQHcyIbwvJLs6
  template:
    metadata:
      name: rabbitmq-connection
      namespace: luxe-infra
