---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-connection
  namespace: luxe-backend
spec:
  encryptedData:
    REDIS_URL: AgC+Ysyjx2NEIHbN4NzTdFytS2SyqEVwcezMEKsvSz2omE6bPZIS88k291K+luLWJGa8dboWQCA3z6L+JL+nVmo7y82P5H9OBEetKHtqgG2V6jxb/tXwTWlZy/flatEhc3ztB6QlwoAdV0eYx+fXduJu3qKVJ8Jp4M+C7oEP7uiDZlEOVs986uQ0Gq+D/smntx3d6CI6D+gRPJRcGnL4B6MXL0LEEEwEoz3dKj13I9ksfX1J+cIOSa5nuTVzqFBXVIWJaqgOsLGXAVgFjyFrX9PxlANu4LEoQ4iWWBX6YydpRJ2r4JsAG8ap1doUit3WuV3YIhIKHpJ1iulN2tQx+2lbyR9kecHbYh/4Ug3tqVSaXa5tdVMI/GjNMSyPfXq4dojZ6RL//rKTuRLF8nngDkWuzZxj0k7LiWg4aplXbLmAA8CDT9hP3jIsPNpYrwfp5iNAsSpMpqUNw1l7UGGHPSrxQ0EgC/a8t1rmafU7xJz3X5cMc9skfypHYF6vwLHa23mxp0g9hunj3nzZcHpWitplRJi6tFiUyhL+eS40wIQsDpuP4hB6rUTmzsyHzHcJs9IcHwdrg0ZxxZV71RTOeTLuH6IH+JkSNMLQ8KAXSbjjaq8oHUqz74a5MqexTZpiCz7dVq7iV/Wtv2VldJn3Nv+bED9oUy5n9bMbLeFGNHQ30IhnPOybg01CrHw804O3YYxkkbtlRkr6BRtANUDBwACnTiLUYLmcOc67l2l+XCkPqeuEC4EiBdwVafWYhljo7usAumjw3yX86k7yGLzWyQTc8dvJqMb0RdHQ
  template:
    metadata:
      name: redis-connection
      namespace: luxe-backend
