---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-connection
  namespace: luxe-infra
spec:
  encryptedData:
    REDIS_URL: AgB+8kVrbLuwmWnGIEClEPhpOYzvzm5zOyJHQkGX75yy1GcPibNdnOzKpLdIEigWk0dbZrsgHWFHNoy/t3e+ZbK94HxWv1aL8BHIJno2IudwnUKCuR8/CNqwW1tKfOQZsyWh6qqhJ7M9km7UXLxRivBMki4a/oODi2ZrD5KMDjPbmWIWOSlo39Q2Z0aInw3i3+gngv5vUm0Qs2zP15hiNMSTHwPjt8p6HRGEFcKVk24krO85ElSbY1IniR/iDhG0S1SgvQsGOWMKvUQuWFoC8PJSbCRJ3o/bV5b4Ab7QrGpXXfjUWLqBJi7vDI7lBXAAsSGRqTsvBzc1FSzAX1CECEnuyopghTO5tuGZcPYFpPF4XHwiEnTEAHALZsadTfmvT90Kc161G/5Jz2t8g+mQg5hi+VofxN+JnksUgmPISNZH6zd5PsbxBo6HxxP7u4sVLv39DZglXOpYygr3p9yJQFszJ8CAePungfjU6+UuSuj8G6utRd5YFsxKawmxeNG6KRKuHGv9u9M7dXHpWoT/0k2HU/3rbsdb/2eMU4MOJOMFuzjYQKFbCIlUvcCLR5kxMlVKgk5P/OC2FNJWk59OY6ZeE31e7dL+VfBhWK2FuZW87H6Z7ZzZyPWB/RpIf7lW78kDKi20A0iItv827exWpcL1126kKIQGdYxmdHaFihHlK/C4qGjs+5AgF3ypvx/f2oedDGkQ0lSEKbqIN/QTfdToc40zeLPu7veOE1f31pBxdv5G9LW7rcB1fSSJPbdPgIRtzbneF5v5JsmW9U1RFCs/PUsWtMaKUz2J
  template:
    metadata:
      name: redis-connection
      namespace: luxe-infra
