---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-secret
  namespace: luxe-infra
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgBmbqtSFZpQ8Mud+miX7SVZbm+fC7/c6ZSLyDMCidABnE5HzteoYLGoxNontnfdzkDir4N0y1QqAr/d7rVK/wP+34QZsBqHrjLjTA2M9QmxbEnvrqbYB3RQy5GW+Cxcwon4GdeNfcyJJVVGLsJRyd+JdCSU4oH/Uc710HSU0zD64kxnTXB4gjK5wR+cL0dbqE8lgSc+78PH3TTK0jbV/w+ROUv9vi/l4Nfi7wp6d4TDYCLJ5NTzGzM3Fa6Iiodsi6d0t3mCAZVulb79K/3l0ekB32qJZiIcYHN1YowSFi08OzE6dQ/0b/v/YcamF78mmKwoOPLwVGegoH75Xj8uF1AT8Phw2u39JFuUPnUg+7yRPCKw9vwG9NlDo2Ha73gqnPwClV42nb8CQw4EeAKAgk8GcdHIDyLKTDd7vYSbdikp1lDXlrJkGoh3svRakzM4EmQa33sN8ZSyhd+kE3gWcT1BjPMW6dYSkPmq8E7GJZozdT35vVfIWTkeJQ76kAHjpef3dbySyBI73sf3e/96OvYqSRRi4+7Z4Ki4EpBtYS3O41fL3TWDmKFCjxqb3sRhhedBhD6jFOApAicXGB3ccuwHGLkKIWJXzFwu2Tb8eRoL19hWUKUi/58YbocOAK8VAtdwk3gyNtzT5ZERELKGQx+g677qv5hJR2iUqjrXQaS+zAgFJqQvdVwEsGse8mNl+fLrQSeOZ+IhPKhkd7skID0bABwgKJqkZjE/hwOeAhE=
    MONGO_INITDB_ROOT_USERNAME: AgAVDCSmWX+YZw9DuoNW41ZvXaAqXxpmybH/nUswee2mjR2B2JjxsqmEu7VY37lSRLlHUNqbJ37yW1JNwGHmV7YtEsserR5gLHDMlj7OlAK4h5SXiMSqgMJ6byP7f50SZnDJC3hGrg7iQExcOrJsl+p+uTSHCQyaaYRAaKRdsaXFmSxflv0tU3KPStY8qBiqg9+/6zsa4y0Yhl+xtjz3jL9uDkTp9FFZnTDUtH0uOyJ4DbRfMUOBtdBznPjNEIrBLK7zUn1dYMsZUI1XH+ZpD4WR8ZOCTl8Ks+UKsraVc96u78VG6bMtHMvLbGkGwQsOOLUeRNIKB8tM0G7XBbYs6IPc10HEzG92e+uCi5WWlrmoLzeifreIbxWt16aIEhy7ekrZ1+xJiepYkUEm3vLr+H7wtu4CzoQZiwpInPiaIHMl/CnalgF6zVbmqUjs36By/yaHvnHrenSlAbQAbde3dxRGhsvkmeP38oZ1bu4xsNVm+e4oWmMYhD3YplDC0m+SfUjtPG17jU8pEO/3SYkUYDyJ/gkWZM/h+i8jNPaTD2XyzxepDr6Vl19/GEcDJEXp8atNlhFQExn+bHeAi46uwOnFbJuyzyYNrWyzZ6cRochjkPaoh02lBtqHlLk3p6otuHI0y5i9jj+JzI+ywtptJVLgUIHItzwa0TXf5YbrJgKavecIOyz/f/IZPuS6HUDFgypxWUydIVJgszU=
  template:
    metadata:
      name: mongodb-secret
      namespace: luxe-infra
