---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: luxe-infra
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgCI6oaqzwsPtEmnH7fuuhkJB+2Q9GviymmkUQu8kU/1pXPjebgyFKzpBRfsQgs7sUhJ5XomrcfC2dNXnqxGuGZcxZsT5rNxZVTy2Uw0RUmi3HAZfdTf0oGXpWIfCBnPgdF3tYqT3yM/rQjlwxNu8kDz2DqF3vLTjMjW0z7fQ4Arpj+PNxtnJQdvVUMkGptEWFcdz1otmtYc7VttXwYr8VWlS5tj8AnYhqPPOf7ss2rcJ7nC1UZiwHfUJ/8YL+/PfAGWSTwEE8m339151s5YHDANj1nbYU6rVCdbS/Yr/aVeqENEuEN8AuDE7Rs43trIHkDdgn1sXE3LBgUzFRMF8RwI2jdnhhBAbqwXwNNuQDqMwY0hVmLSaMxnYHFp0+qFtYw9TcAa3lfYMRzOha+eQqG7zBmb66ibgJRBlYcVc6ATS/e0G0itUSolwrSTR/uH205nnPcBhDGVw+GlwFj/dr2Lrn/qL4EFALZvqrpViSxaCR8wOdkGaaOh/HF8qzVDxhXylDn2gxr7Pt+LTYCr8HWFX3fWOamIc+zQxp5LDYmwzUeVcvEEqtcaMomni3L9rl4Li0jb0dhCiGgDGx0pn+yLaghjd5Mc0Zotjpd1rWA6trHWk1OxntIYPKIggIhE84tvWvtliWyF+VbzK4TMjA9TSVMSfUdjRtmBlfOAZBYLsKcs6ojnMBC1DDu96aKcVygPwkVII6j6bm9CCzF6bRmV4Fz8MbvN
    RABBITMQ_DEFAULT_USER: AgAn8l6hY0QteDnPUnyxUKcdx4rlzSE0WWuHuRmEZWr4A1PAWdRTV/7hOmmecI3AEY5IFczAqf6KGBcI6FP0ZqG16YWtqdP4a/Ewb5JBK3Er5NNIIAWnmYjx5iEXVRZVOwMVhPPzusdr/3CnlkB3/T8zg84HR9RHKfOSXeNfosczU12HzTKCFxnWTtQJkzmEp7csUhvIEw9G01iYqM2ueNBQCSQou9BipxNpGWVH2cK1B8Ial9nDvrkMaYzusHJyZENa1nJG0Z62B3ydrJuDYYnD5tyw25ZFtnq/0PBiOVQAQW8hVM4dbvyNPtG4pOex12Gw1PnUH8ncDuyxEnAyrt422hFvyaIiCWdDpgLCqsgSKMTbifuEIcTcQ0BmZFuXD1cCOuz31sU6wXfluLrIS+7K0crsd8nDLrmOV6ct1bYlw3b71QtoequBnUYIL49gV7hTPHG9q9k3f2O7lO1sFkUdr+xwtCy5beksxPwsmIbtIs88SOEBqRxKS7H9fK4PIJB1l4A9fZSlT6mkB90bTI+AzOMaHOty1AoGW/tZ3q5PrG8c0/3A2u3VFON6OLr71VFIgr3rXvNmA5wORuzDMmsAaWJczHP4B/bdD8l4IaNqRxh4sJovXdI3wCOISDm8gdsZNIKBwRN+NOvx3SX5DjqyPLGa2MxsF14eJdedNungrIMYW/fUrWRwCRG08bi+ABbOPyu1y0W7p6U=
  template:
    metadata:
      name: rabbitmq-secret
      namespace: luxe-infra
