---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: luxe-infra
spec:
  encryptedData:
    REDIS_PASSWORD: AgC9+lnzJVOEJLsogjvr19qg+Bk4XTGUKwK4Iv1ejiXOCWinlU6h4TFzx4SIDDgRFS8CvD64keOFzZ+LzFg1l7q7ldT/xiQ4GHJt6Vg6bPnnmF1dgYmpl41mbeMx6b+SVTN/oHhrJPCrmx67CsIOlnt24U1P+9ER5VOodOjAabWE0GOHEhWym0/q6ynAVas2USgFeu2H0+XWHU6Lyzapka9QVMt6Lh9ORc5ShEzQH5IjWoOYxQpzUYvRH9uWT2kUT49FSW8bQ1MTRXkwpW+JsOaCo5ixLkHbf+VT0/TRkcTj4QhzxgjFbVGR3JJ15LVibyefk7M7MAKVIRwBh0iW0kzijzTPF+9nkusUF8dZAbbpiUbupS3RaGhS4zrWfW1fcbX6i+W1UkmKrYYP7wJeVCOpjJ1RxuqLoOy1meHTZX5f7uYsCA4cKgP2LSeKpoICsGIx5LCMbiV2HXuQbOBKSDyDwo7aJ56Ic/7eayMQJUQQ0jyGM+QmvInmc4Zrw6RUegOe3gZ6o7OKdlb3TJt4yL6OPCHrpYSdc2wMuSpgqMytXtxtU/pghnLdKhseXYHKNgnWmZGQXTi/nxOEyPOewO8+4rsqsTB2DOWAgWdnpJbxGC1zX/QIAvwa9X5GLdrCkBLPJX0hWnQLRu5kacqFQgigSVerkRRYRpG3D5Et8D1BlSHtJfPM8ujmIBdpi6ThgpPdTuKwK0RfHCCBMjonL1N6nLCAiv2RX4w=
  template:
    metadata:
      name: redis-secret
      namespace: luxe-infra
